#!/usr/bin/env bash
# Installs and configure Nginx web server
# shellcheck disable=SC2016

contents='server {
	listen 80 default_server;
	listen [::]:80 default_server;
		root /var/www/html;
	# Add index.php to the list if you are using PHP
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}

	if (\$request_filename ~ redirect_me) {
		rewrite ^ https://www.google.com/ permanent;
	}
}
'

apt-get update
apt-get -y install nginx
ufw allow 'Nginx FULL'
echo 'Hello World!' > /var/www/html/index.html
echo "$contents" > /etc/nginx/sites-enabled/default
service nginx restart
