#!/usr/bin/env bash
# Installs and configure Nginx web server
# shellcheck disable=SC2016
# shellcheck disable=SC1004

# redirect='    location \/ {\
# 	    try_files $uri $uri\/ =404;\
# 	}\
# \
# 	location \/redirect_me {\
# 		return 301 https:\/\/www.google.com\/;\
# 	}\n'

redirect='    location \/redirect_me {\
		return 301 https:\/\/www.google.com\/;\
	}\
\
	location \/ {'

apt-get update
apt-get -y install nginx
ufw allow 'Nginx FULL'
echo 'Hello World!' > /var/www/html/index.html
sed -i "s/^\s*location\s*\/\s*{\s*$/$redirect/" /etc/nginx/sites-enabled/default
service nginx restart
