#!/usr/bin/env bash
# Installs and configure Nginx web server
# shellcheck disable=SC2016
# shellcheck disable=SC1004

config='    location \/redirect_me {\
		return 301 https:\/\/www.google.com\/;\
	}\
\
	error_page 404 \/404;\
	location  \/404 {\
            internal;\
	}\
\
	location \/ {'

apt-get update
apt-get -y install nginx
ufw allow 'Nginx FULL'
echo 'Hello World!' > /var/www/html/index.html
echo 'Ceci n'\''est pas une page' > /var/www/html/404
if [ $(grep -e "^\\s*location\\s*/404\\s*" /etc/nginx/sites-enabled/default | wc -l) -eq 0 ]; then
	sed -i "s/^\s*location\s*\/\s*{\s*$/$config/" /etc/nginx/sites-enabled/default
fi
service nginx restart
