#!/usr/bin/env bash
# Installs and configure Nginx web server
# shellcheck disable=SC2016
# shellcheck disable=SC1004

redirect='    location \/redirect_me {\
		return 301 https:\/\/www.google.com\/;\
	}\
\
	error_page 404 \/404;\
	location  \/404 {\
            internal;\
	}\
	location \/ {'

apt-get update
apt-get -y install nginx
ufw allow 'Nginx FULL'
echo 'Hello World!' > /var/www/html/index.html
echo 'Ceci n'\''est pas une page' > /var/www/html/404
sed -i "s/^\s*location\s*\/\s*{\s*$/$redirect/" /etc/nginx/sites-enabled/default
service nginx restart
