#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely
# Displays "I am invincible!!!" if SIGTERM signal is received

trap "echo 'I am invincible!!!'" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
