#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

i=1
while [ $i -le 100 ]
do
    if [ $(( i % 3 )) -eq 0 ] || [ $(( i % 5 )) -eq 0 ]
    then
	if [ $(( i % 3 )) -eq 0 ]
	then
	    echo -n "Fizz"
	fi

	if [ $(( i % 5 )) -eq 0 ]
	then
	    echo -n "Buzz"
	fi
    else
	echo -n "$i"
    fi

    echo ""
    (( i++ ))
done

exit 0
