#!/usr/bin/env bash
# displays the contents of the file /etc/passwd

fn='/etc/passwd'

while
    read -r line
do
    shopt -s lastpipe
    echo "$line" | tr "\n" "\0" | mapfile -d ':' -t data
    echo "The user ${data[0]} is part of the ${data[3]} gang, lives in ${data[5]} and rides ${data[6]}. ${data[2]}'s place is protected by the passcode ${data[1]}, more info about the user here: ${data[4]}"

done < "$fn"

exit 0
