#!/usr/bin/env bash
# This bash script configures an Ubuntu server with the below requirements:
# * localhost resolves to 127.0.0.2
# * facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.mod
sed -i 's/^.*localhost$/127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com/' ~/hosts.mod
cp -f ~/hosts.mod /etc/hosts && rm ~/hosts.mod
