#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the following requirements:
# -> localhost resolves to 127.0.0.2
# -> facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts
sed -i 's/^127.0.0.2\slocalhost$/127.0.0.1\tlocalhost/' ~/hosts
sed -i 's/8.8.8.8\s*facebook.com//' ~/hosts
cp -f ~/hosts /etc/hosts