#!/usr/bin/env bash
# This script makes sure that Nginx is running as the nginx user and listens to port 8080

pkill -9 -f apache2
# chown nginx:nginx /usr/sbin/nginx /etc/nginx/nginx.conf
chmod 664 /etc/nginx/nginx.conf
sed -i "1i user nginx;" /etc/nginx/nginx.conf
sed -i -E 's/([ :])80 /\18080 /' '/etc/nginx/sites-available/default'
# echo 'service nginx start' | sudo -u nginx -i
sudo -u nginx service nginx restart
