#!/usr/bin/env bash
# This script makes sure that Nginx is running as the nginx user and listens to port 8080
chmod 664 /etc/nginx/nginx.conf
sed -i "1i user nginx;" /etc/nginx/nginx.conf
sed -i -E 's/([ :])80 /\18080 /' '/etc/nginx/sites-available/default'
pkill -9 -f apache2
sudo -u nginx service nginx restart
