#!/usr/bin/env bash
# This script makes sure that Nginx is running as the nginx user and listens to port 8080
pkill -f .*apache2.*
chown nginx:nginx /usr/sbin/nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i -E 's/listen\s*80\s*default_server;/listen 8080 default_server;/' '/etc/nginx/sites-available/default'
echo 'service nginx start' | sudo -u nginx -i
