#!/usr/bin/env bash
# This script reloads Gunicorn in a graceful way

# pid="$(sudo systemctl show --property MainPID --value gunicorn)"
# kill -1 "$pid"

# sudo pkill -SIGHUP gunicor[n]

sudo kill -1 "$(sudo systemctl show --property MainPID --value gunicorn)" 
