#!/usr/bin/env bash
# This script reloads Gunicorn in a graceful way

# pid="$(pgrep gunicorn | head -n1)"
# pid="$(sudo systemctl show --property MainPID --value gunicorn)"
# kill -1 "$pid"
kill -HUP "$(sudo systemctl show --property MainPID --value gunicorn)"
