#!/usr/bin/env bash
# This script configures application server using flask, Gunicorn and Nginx

# Check if required pkgs exists and install missing packages
to_install='python3-dev'
progs=( 'python3' 'pip3' 'nginx' )

for prog in "${progs[@]}"
do
    if ! which "$prog" > /dev/null 2>&1 ; then
        to_install="$to_install $prog"
    fi
done
echo "Installing the following packages: $to_install"
echo

sudo apt update
sudo apt install -y "$to_install"

# Check if required pip3 pkgs exists and install missing packages
to_install=''
pkgs=( 'gunicorn' 'flask' )

for pkg in "${pkgs[@]}"
do
    if ! pip3 show "$pkg" > /dev/null 2>&1 ; then
        to_install="$to_install $pkg"
    fi
done


if [ -n "$to_install" ] ; then
    echo "Installing the following pip3 packages:$to_install"
    pip3 install $to_install
fi


# Configure the firewall to allow traffic through application servers port
sudo ufw allow 5000/tcp
